### ISSUE TITLE
Checkout Stack working with Stripe

### ISSUE THREAD

**Issue by tiggyh** [yuzoolcode/yuzoolthemes-tracking#25]
I am using the most up to date version of the Checkout stack for rapid weaver (1.0.6) and am using it for the 'Custom Amount'. I have all the test keys entered correctly but I get the error: 

'The Stripe Token Was Not Generated Correctly' 

The dashboard log reports that it made a successful connection but it doesn't get further than that in making a successful test payment.
<img width="424" alt="Screenshot 2019-05-16 18 25 55" src="https://user-images.githubusercontent.com/50714088/57874268-16da7d80-7808-11e9-873d-2edbeab9c6c3.png">

Any help would be greatly appreciated.

**Comment by yuzoolcode** [comment]
The online demo works:
http://demo.yuzoolthemes.com/checkout/page-5/

So I'm guessing something has gone wrong and needs a fix or setting change. 
Will test and update soon

**Comment by yuzoolcode** [comment]
Thanks again for the bug report - have found an error and will ship an update hopefully today

**Comment by yuzoolcode** [comment]
Fixed and shipped 

- Fix for One-time amounts showing errors
- Fix also for custom amount showing errors

**Comment by MoSohi** [comment]
Thank you for the update. I reported this bug weeks ago.
I still see the separator field has a little problem. Please see what I put and what I get in these below screenshots.
Please advise
![Screen Shot 2019-05-17 at 08 46 44](https://user-images.githubusercontent.com/48636132/57929353-192cee00-7881-11e9-850d-b368ba35b511.png)
![Screen Shot 2019-05-17 at 08 47 03](https://user-images.githubusercontent.com/48636132/57929354-192cee00-7881-11e9-8667-2110029f8d8b.png)

**Comment by yuzoolcode** [comment]
You reported it where?
https://github.com/yuzoolcode/yuzoolthemes-tracking/issues?q=is%3Aissue+is%3Aclosed

**Comment by yuzoolcode** [comment]
@MoSohi 
That bug I'm not able to replicate

![RapidWeaver 2019-05-18 at 07 59 00](https://user-images.githubusercontent.com/4608547/57960318-fd8a1c00-7942-11e9-8e0a-d1526ae482fb.jpg)

Are you pressing "return" - it looks like you have the text field editable. But as you can see from these screens once I press "return" it changes the text:

Editing:
![RapidWeaver 2019-05-18 at 07 59 39](https://user-images.githubusercontent.com/4608547/57960331-1266af80-7943-11e9-9642-0fc1fab3f976.jpg)

Return pressed:
![RapidWeaver 2019-05-18 at 07 59 46](https://user-images.githubusercontent.com/4608547/57960336-1c88ae00-7943-11e9-995a-269235a94068.jpg)

**Comment by MoSohi** [comment]
> You reported it where?
> https://github.com/yuzoolcode/yuzoolthemes-tracking/issues?q=is%3Aissue+is%3Aclosed

Right Here. #18

**Comment by MoSohi** [comment]
> @MoSohi
> That bug I'm not able to replicate
> 
> ![RapidWeaver 2019-05-18 at 07 59 00](https://user-images.githubusercontent.com/4608547/57960318-fd8a1c00-7942-11e9-8e0a-d1526ae482fb.jpg)
> 
> Are you pressing "return" - it looks like you have the text field editable. But as you can see from these screens once I press "return" it changes the text:
> 
> Editing:
> ![RapidWeaver 2019-05-18 at 07 59 39](https://user-images.githubusercontent.com/4608547/57960360-4b9f1f80-7943-11e9-89ad-0a85ccaacaf0.jpg)
> 
> Return pressed:
> ![RapidWeaver 2019-05-18 at 07 59 46](https://user-images.githubusercontent.com/4608547/57960363-4e9a1000-7943-11e9-8638-6abe5bca8efb.jpg)

Thank you for reply.
For me, In this new recent update, it does not matter what you put in separator field, you always get "Pay By CC".
Please check & advise.

**Comment by tiggyh** [comment]
> Fixed and shipped
> 
> * Fix for One-time amounts showing errors
> * Fix also for custom amount showing errors

Thank you very much indeed, much appreciated :)

**Comment by yuzoolcode** [comment]
@MoSohi I've checked in the latest version and it seems to work 

- Can you verify you are running the latest version?
- Do you have anymore details?

Here's a video of it working:
https://www.dropbox.com/s/334xxskytobyyh9/CleanShot%202019-05-19%20at%2021.06.26.gif?dl=1

**Comment by MoSohi** [comment]
> @MoSohi I've checked in the latest version and it seems to work
> 
> * Can you verify you are running the latest version?
> * Do you have anymore details?
> 
> Here's a video of it working:
> https://www.dropbox.com/s/334xxskytobyyh9/CleanShot%202019-05-19%20at%2021.06.26.gif?dl=1

Thank you for re-checking.
I deleted the stack in my website and re-creat a new one.
Works like a charm.
Thank you again.

**Comment by MoSohi** [comment]
> @MoSohi I've checked in the latest version and it seems to work
> 
> * Can you verify you are running the latest version?
> * Do you have anymore details?
> 
> Here's a video of it working:
> https://www.dropbox.com/s/334xxskytobyyh9/CleanShot%202019-05-19%20at%2021.06.26.gif?dl=1

Thank you for re-checking.
I deleted the stack in my rapid weaver file and created a new one.
Works like a charm.
Thank you again.

**Comment by yuzoolcode** [comment]
Great @MoSohi  ^ good to hear!
